name: Monthly Economic Update & Alert

on:
  workflow_dispatch:
    inputs:
      tw_cpi:
        description: 'TW CPI'
        default: '0.0'
      us_cpi:
        description: 'US CPI'
        default: '0.0'

jobs:
  run_monitor:
    runs-on: ubuntu-latest
    # --- 將 env 放在這裡，確保全域生效 ---
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      DB_URL: ${{ secrets.DB_URL }}
    # ----------------------------------
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install yfinance pandas sqlalchemy pymysql

      - name: Execute Script
        run: python crawler_and_calc.py ${{ github.event.inputs.tw_cpi }} ${{ github.event.inputs.us_cpi }}
